// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw1anYZYUXRH83ZqvSJYuOfhv5zCDwbDE',
    appId: '1:607522445475:web:8b790db166b4d3f3d88716',
    messagingSenderId: '607522445475',
    projectId: 'chosun-map',
    authDomain: 'chosun-map.firebaseapp.com',
    storageBucket: 'chosun-map.firebasestorage.app',
    measurementId: 'G-NQB9JCYMXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9w5p2bAXn6qLg3LnNm0G3TC0dyOrPiw',
    appId: '1:607522445475:android:ad0b1137d540ff4cd88716',
    messagingSenderId: '607522445475',
    projectId: 'chosun-map',
    storageBucket: 'chosun-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPFqnMmK4GTsXFVJH3Vi5j-9BHhRGLExI',
    appId: '1:607522445475:ios:cfa80f1f1f8dc77cd88716',
    messagingSenderId: '607522445475',
    projectId: 'chosun-map',
    storageBucket: 'chosun-map.firebasestorage.app',
    iosBundleId: 'com.example.campusMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPFqnMmK4GTsXFVJH3Vi5j-9BHhRGLExI',
    appId: '1:607522445475:ios:cfa80f1f1f8dc77cd88716',
    messagingSenderId: '607522445475',
    projectId: 'chosun-map',
    storageBucket: 'chosun-map.firebasestorage.app',
    iosBundleId: 'com.example.campusMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw1anYZYUXRH83ZqvSJYuOfhv5zCDwbDE',
    appId: '1:607522445475:web:840b9adf8b6f11b2d88716',
    messagingSenderId: '607522445475',
    projectId: 'chosun-map',
    authDomain: 'chosun-map.firebaseapp.com',
    storageBucket: 'chosun-map.firebasestorage.app',
    measurementId: 'G-ZB1YWJTV4H',
  );
}
